//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveRequest.WPF.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TakeLeave
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTimeOffset> Date_Start { get; set; }
        public Nullable<System.DateTimeOffset> Date_End { get; set; }
        public string Approval_Status { get; set; }
        public Nullable<int> Difference { get; set; }
        public Nullable<System.DateTimeOffset> Date_Start_Special { get; set; }
        public Nullable<System.DateTimeOffset> Date_End_Special { get; set; }
        public Nullable<int> Difference_Special { get; set; }
        public int Employee_Id { get; set; }
        public int Leave_Id { get; set; }
        public System.DateTimeOffset CreateDate { get; set; }
        public System.DateTimeOffset UpdateDate { get; set; }
        public System.DateTimeOffset DeleteDate { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Leave Leaf { get; set; }
    }
}
